import "dotenv/config";
import { ObjectId } from "mongodb";
import { getDb } from "./mongodb";

const ROLES = {
  // 1. Basic Roles
  BASIC_ROLES: new ObjectId("670000000000000000000020"),
  LOGIN: new ObjectId("670000000000000000000002"),
  PROFILE: new ObjectId("670000000000000000000021"),
  EDIT_PROFILE: new ObjectId("670000000000000000000022"),
  UPDATE_PASSWORD: new ObjectId("670000000000000000000023"),

  // 2. System
  SYSTEM: new ObjectId("670000000000000000000001"),
  GROUPS: new ObjectId("670000000000000000000008"),
  LIST_GROUP: new ObjectId("670000000000000000000024"),
  ADD_GROUP: new ObjectId("670000000000000000000009"),
  EDIT_GROUP: new ObjectId("67000000000000000000000a"),
  ROLE_GROUP_MANAGEMENT: new ObjectId("67000000000000000000000b"),

  USERS: new ObjectId("670000000000000000000003"),
  LIST_USER: new ObjectId("670000000000000000000025"),
  ADD_USER: new ObjectId("670000000000000000000004"),
  EDIT_USER: new ObjectId("670000000000000000000005"),
  USER_DETAIL: new ObjectId("670000000000000000000006"),
  KICKOUT_USER: new ObjectId("670000000000000000000007"),

  SYSTEM_LOGS: new ObjectId("67000000000000000000000c"),
  REDIRECTS: new ObjectId("67000000000000000000000d"),
  SETTINGS: new ObjectId("67000000000000000000000e"),
  RECEIVE_SYSTEM_ALERTS: new ObjectId("67000000000000000000000f"),

  // 3. Dashboard
  DASHBOARD: new ObjectId("670000000000000000000100"),
  OVERVIEW: new ObjectId("670000000000000000000110"),
  ANALYTICS: new ObjectId("670000000000000000000111"),
  SYSTEM_REPORT: new ObjectId("670000000000000000000101"),
  USER_GROUP_REPORT: new ObjectId("670000000000000000000102"),

  // 5. Accounting
  ACCOUNTING: new ObjectId("670000000000000000000200"),
  COA: new ObjectId("670000000000000000000201"),
  ADD_COA: new ObjectId("670000000000000000000202"),
  EDIT_COA: new ObjectId("670000000000000000000203"),
  ACCOUNT: new ObjectId("670000000000000000000204"),
  ADD_ACCOUNT: new ObjectId("670000000000000000000205"),
  EDIT_ACCOUNT: new ObjectId("670000000000000000000206"),
  ACCOUNT_DETAIL: new ObjectId("670000000000000000000207"),
  TRANSACTION: new ObjectId("670000000000000000000208"),
  CREATE_TRANSACTION: new ObjectId("670000000000000000000209"),
  EDIT_TRANSACTION: new ObjectId("67000000000000000000020a"),
  CONFIRM_TRANSACTION: new ObjectId("67000000000000000000020b"),
  LEDGER: new ObjectId("67000000000000000000020c"),
  BALANCE_SHEET: new ObjectId("67000000000000000000020d"),
  BALANCE_SHEET_PDF: new ObjectId("67000000000000000000020e"),
  BALANCE_SHEET_XLSX: new ObjectId("67000000000000000000020f"),
  INCOME_STATEMENT: new ObjectId("670000000000000000000210"),
  INCOME_STATEMENT_PDF: new ObjectId("670000000000000000000211"),
  INCOME_STATEMENT_XLSX: new ObjectId("670000000000000000000212"),
  CLOSING: new ObjectId("670000000000000000000213"),
  COA_PDF: new ObjectId("670000000000000000000214"),
  COA_XLSX: new ObjectId("670000000000000000000215"),
  ACCOUNT_PDF: new ObjectId("670000000000000000000216"),
  ACCOUNT_XLSX: new ObjectId("670000000000000000000217"),
  UPLOAD_EVIDENCE: new ObjectId("670000000000000000000218"),
  CASH_FLOW: new ObjectId("670000000000000000000219"),
  EQUITY_CHANGES: new ObjectId("67000000000000000000021a"),

  // 6. Content
  CONTENT: new ObjectId("670000000000000000000300"),

  // 4a. Posts
  POSTS: new ObjectId("670000000000000000000310"),
  LIST_POST: new ObjectId("670000000000000000000311"),
  CREATE_POST: new ObjectId("670000000000000000000312"),
  EDIT_POST: new ObjectId("670000000000000000000313"),
  VIEW_POST: new ObjectId("670000000000000000000314"),
  DELETE_POST: new ObjectId("670000000000000000000315"),
  BULK_POST: new ObjectId("670000000000000000000316"),
  GENERATE_POST: new ObjectId("670000000000000000000317"),
  FIX_POST: new ObjectId("670000000000000000000318"),

  // 4b. Pages
  PAGES: new ObjectId("670000000000000000000320"),
  LIST_PAGE: new ObjectId("670000000000000000000321"),
  CREATE_PAGE: new ObjectId("670000000000000000000322"),
  EDIT_PAGE: new ObjectId("670000000000000000000323"),
  VIEW_PAGE: new ObjectId("670000000000000000000324"),
  DELETE_PAGE: new ObjectId("670000000000000000000325"),
  BULK_PAGE: new ObjectId("670000000000000000000326"),
  FIX_PAGE: new ObjectId("670000000000000000000327"),

  // 4c. Categories
  CATEGORIES: new ObjectId("670000000000000000000330"),
  LIST_CATEGORY: new ObjectId("670000000000000000000331"),
  CREATE_CATEGORY: new ObjectId("670000000000000000000332"),
  EDIT_CATEGORY: new ObjectId("670000000000000000000333"),
  BULK_CATEGORY: new ObjectId("670000000000000000000334"),

  // 4d. Media
  MEDIA: new ObjectId("670000000000000000000340"),
  LIST_MEDIA: new ObjectId("670000000000000000000341"),
  UPLOAD_MEDIA: new ObjectId("670000000000000000000342"),
  VIEW_MEDIA: new ObjectId("670000000000000000000343"),
  DELETE_MEDIA: new ObjectId("670000000000000000000344"),
  BULK_MEDIA: new ObjectId("670000000000000000000345"),

  // 4e. Ads
  ADS: new ObjectId("670000000000000000000350"),
  LIST_AD: new ObjectId("670000000000000000000351"),
  CREATE_AD: new ObjectId("670000000000000000000352"),
  EDIT_AD: new ObjectId("670000000000000000000353"),
  DELETE_AD: new ObjectId("670000000000000000000354"),
  BULK_AD: new ObjectId("670000000000000000000355"),
};

const ADMIN_GROUP = new ObjectId("670000000000000000000010");
const ALL_ROLE_IDS = Object.values(ROLES);

async function seed() {
  const db = await getDb();
  const groups = db.collection("systemGroups");
  const roles = db.collection("systemRoles");
  const groupHasRole = db.collection("systemGroupHasRole");

  // Drop collections entirely (removes data + indexes)
  await roles.drop().catch(() => {});
  await groupHasRole.drop().catch(() => {});

  const now = new Date();

  await groups.updateOne(
    { _id: ADMIN_GROUP },
    {
      $setOnInsert: {
        _id: ADMIN_GROUP,
        name: "Administrators",
        description: "Full system access",
        created: { at: now, by: null },
        updated: { at: now, by: null },
      },
    },
    { upsert: true }
  );

  const roleDocs = [
    // ─── 1. Basic Roles ──────────────────────────────────
    {
      _id: ROLES.BASIC_ROLES,
      parent: null,
      name: "Basic Roles",
      description: "Root basic access roles",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.LOGIN,
      parent: ROLES.BASIC_ROLES,
      name: "Login",
      description: "When disabled, users cannot sign in",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.PROFILE,
      parent: ROLES.BASIC_ROLES,
      name: "Profile",
      description: "View user profile details",
      url: "/account/profile",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.EDIT_PROFILE,
      parent: ROLES.PROFILE,
      name: "Edit Profile",
      description: "Edit user profile page",
      url: "/account/profile/edit",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.UPDATE_PASSWORD,
      parent: ROLES.BASIC_ROLES,
      name: "Update Password",
      description: "Change user profile password",
      url: "/account/password",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },

    // ─── 2. System ───────────────────────────────────────
    {
      _id: ROLES.SYSTEM,
      parent: null,
      name: "System",
      description: "Root system administration module",
      url: "/system",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.GROUPS,
      parent: ROLES.SYSTEM,
      name: "Groups",
      description: "Groups administration module",
      url: "/system/group",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.LIST_GROUP,
      parent: ROLES.GROUPS,
      name: "List Group",
      description: "View groups directory list",
      url: "/system/group",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.ADD_GROUP,
      parent: ROLES.GROUPS,
      name: "Add Group",
      description: "Create new user groups",
      url: "/system/group/add",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.EDIT_GROUP,
      parent: ROLES.GROUPS,
      name: "Edit Group",
      description: "Modify existing group parameters",
      url: "/system/group/edit",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.ROLE_GROUP_MANAGEMENT,
      parent: ROLES.GROUPS,
      name: "Role Group Management",
      description: "Modify permissions linked to a group",
      url: "/system/group/role",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.USERS,
      parent: ROLES.SYSTEM,
      name: "Users",
      description: "Users administration module",
      url: "/system/users",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.LIST_USER,
      parent: ROLES.USERS,
      name: "List User",
      description: "View users directory list",
      url: "/system/users",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.ADD_USER,
      parent: ROLES.USERS,
      name: "Add User",
      description: "Register new system users",
      url: "/system/users/add",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.EDIT_USER,
      parent: ROLES.USERS,
      name: "Edit User",
      description: "Modify existing user accounts",
      url: "/system/users/edit",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.USER_DETAIL,
      parent: ROLES.USERS,
      name: "User Detail",
      description: "Inspect detailed user profile attributes",
      url: "/system/users/detail",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.KICKOUT_USER,
      parent: ROLES.USERS,
      name: "Kickout User",
      description: "Revoke active user login sessions",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.SYSTEM_LOGS,
      parent: ROLES.SYSTEM,
      name: "System Logs",
      description: "View system activity logs",
      url: "/system/logs",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.REDIRECTS,
      parent: ROLES.SYSTEM,
      name: "Redirects",
      description: "Manage 404 redirect rules",
      url: "/system/redirects",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.SETTINGS,
      parent: ROLES.SYSTEM,
      name: "Settings",
      description: "Manage application settings",
      url: "/system/settings",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.RECEIVE_SYSTEM_ALERTS,
      parent: ROLES.SYSTEM,
      name: "Receive System Alerts",
      description: "Receive broadcast notifications for system ERROR and WARN events",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },

    // ─── 3. Dashboard ────────────────────────────────────
    {
      _id: ROLES.DASHBOARD,
      parent: null,
      name: "Dashboard",
      description: "Root dashboard metrics overview",
      url: "/dashboard",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.OVERVIEW,
      parent: ROLES.DASHBOARD,
      name: "Overview",
      description: "System overview stats dashboard",
      url: "/dashboard",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.ANALYTICS,
      parent: ROLES.DASHBOARD,
      name: "Analytics",
      description: "View web analytics and traffic insights",
      url: "/dashboard/analytics",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.SYSTEM_REPORT,
      parent: ROLES.DASHBOARD,
      name: "System Report",
      description: "View system reports and settings logs",
      url: "/dashboard/system",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.USER_GROUP_REPORT,
      parent: ROLES.DASHBOARD,
      name: "User and Group Report",
      description: "View statistics logs on users and groups",
      url: "/dashboard/user-group",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },

    // ─── Accounting ───────────────────────────────────────
    {
      _id: ROLES.ACCOUNTING,
      parent: null,
      name: "Accounting",
      description: "Accounting module access",
      url: "/accounting",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.COA,
      parent: ROLES.ACCOUNTING,
      name: "CoA",
      description: "Manage chart of accounts",
      url: "/accounting/coa",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.ADD_COA,
      parent: ROLES.COA,
      name: "Add CoA",
      description: "Create new chart of accounts entries",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.EDIT_COA,
      parent: ROLES.COA,
      name: "Edit CoA",
      description: "Modify existing chart of accounts entries",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.COA_PDF,
      parent: ROLES.COA,
      name: "Print PDF",
      description: "Download chart of accounts as PDF",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.COA_XLSX,
      parent: ROLES.COA,
      name: "Download Excel",
      description: "Download chart of accounts as XLSX",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.ACCOUNT,
      parent: ROLES.ACCOUNTING,
      name: "Account",
      description: "Manage ledger accounts",
      url: "/accounting/account",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.ADD_ACCOUNT,
      parent: ROLES.ACCOUNT,
      name: "Add Account",
      description: "Create new ledger accounts",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.EDIT_ACCOUNT,
      parent: ROLES.ACCOUNT,
      name: "Edit Account",
      description: "Modify existing ledger accounts",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.ACCOUNT_DETAIL,
      parent: ROLES.ACCOUNT,
      name: "Account Detail",
      description: "View account details",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.ACCOUNT_PDF,
      parent: ROLES.ACCOUNT,
      name: "Print PDF",
      description: "Download accounts list as PDF",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.ACCOUNT_XLSX,
      parent: ROLES.ACCOUNT,
      name: "Download Excel",
      description: "Download accounts list as XLSX",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.TRANSACTION,
      parent: ROLES.ACCOUNTING,
      name: "Transaction",
      description: "Manage journal entries",
      url: "/accounting/transaction",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.CREATE_TRANSACTION,
      parent: ROLES.TRANSACTION,
      name: "Create Transaction",
      description: "Create new journal entries",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.EDIT_TRANSACTION,
      parent: ROLES.TRANSACTION,
      name: "Edit Transaction",
      description: "Modify pending journal entries",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.CONFIRM_TRANSACTION,
      parent: ROLES.TRANSACTION,
      name: "Confirm Transaction",
      description: "Confirm pending journal entries",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.LEDGER,
      parent: ROLES.ACCOUNTING,
      name: "Ledger",
      description: "View general ledger",
      url: "/accounting/ledger",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.BALANCE_SHEET,
      parent: ROLES.ACCOUNTING,
      name: "Balance Sheet",
      description: "View balance sheet",
      url: "/accounting/balance-sheet",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.BALANCE_SHEET_PDF,
      parent: ROLES.BALANCE_SHEET,
      name: "Print PDF",
      description: "Download balance sheet as PDF",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.BALANCE_SHEET_XLSX,
      parent: ROLES.BALANCE_SHEET,
      name: "Download Excel",
      description: "Download balance sheet as XLSX",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.INCOME_STATEMENT,
      parent: ROLES.ACCOUNTING,
      name: "Income Statement",
      description: "View income statement",
      url: "/accounting/income-statement",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.INCOME_STATEMENT_PDF,
      parent: ROLES.INCOME_STATEMENT,
      name: "Print PDF",
      description: "Download income statement as PDF",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.INCOME_STATEMENT_XLSX,
      parent: ROLES.INCOME_STATEMENT,
      name: "Download Excel",
      description: "Download income statement as XLSX",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.CLOSING,
      parent: ROLES.ACCOUNTING,
      name: "Closing",
      description: "Year-end closing",
      url: "/accounting/closing",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.UPLOAD_EVIDENCE,
      parent: ROLES.TRANSACTION,
      name: "Upload Evidence",
      description: "Upload transaction evidence documents",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.CASH_FLOW,
      parent: ROLES.ACCOUNTING,
      name: "Statement of Cash Flows",
      description: "View Statement of Cash Flows",
      url: "/accounting/cash-flow",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.EQUITY_CHANGES,
      parent: ROLES.ACCOUNTING,
      name: "Statement of Changes in Equity",
      description: "View Statement of Changes in Equity",
      url: "/accounting/equity-changes",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },

    // ─── 4. Content ───────────────────────────────────────
    {
      _id: ROLES.CONTENT,
      parent: null,
      name: "Content",
      description: "Root content management module",
      url: "/content",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },

    // ─── 4a. Posts ────────────────────────────────────────
    {
      _id: ROLES.POSTS,
      parent: ROLES.CONTENT,
      name: "Posts",
      description: "Posts management module",
      url: "/content/post",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.LIST_POST,
      parent: ROLES.POSTS,
      name: "List Post",
      description: "View posts directory list",
      url: "/content/post",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.CREATE_POST,
      parent: ROLES.POSTS,
      name: "Create Post",
      description: "Create new posts",
      url: "/content/post/add",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.EDIT_POST,
      parent: ROLES.POSTS,
      name: "Edit Post",
      description: "Modify existing posts",
      url: "/content/post/edit",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.VIEW_POST,
      parent: ROLES.POSTS,
      name: "View Post",
      description: "View post details",
      url: "/content/post/detail",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.DELETE_POST,
      parent: ROLES.POSTS,
      name: "Delete Post",
      description: "Delete existing posts",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.BULK_POST,
      parent: ROLES.POSTS,
      name: "Bulk Post Actions",
      description: "Perform bulk actions on posts",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.GENERATE_POST,
      parent: ROLES.POSTS,
      name: "Generate Post",
      description: "Generate posts using AI",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.FIX_POST,
      parent: ROLES.POSTS,
      name: "Fix Post by AI",
      description: "Improve existing posts using AI",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },

    // ─── 4b. Pages ────────────────────────────────────────
    {
      _id: ROLES.PAGES,
      parent: ROLES.CONTENT,
      name: "Pages",
      description: "Pages management module",
      url: "/content/page",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.LIST_PAGE,
      parent: ROLES.PAGES,
      name: "List Page",
      description: "View pages directory list",
      url: "/content/page",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.CREATE_PAGE,
      parent: ROLES.PAGES,
      name: "Create Page",
      description: "Create new pages",
      url: "/content/page/add",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.EDIT_PAGE,
      parent: ROLES.PAGES,
      name: "Edit Page",
      description: "Modify existing pages",
      url: "/content/page/edit",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.VIEW_PAGE,
      parent: ROLES.PAGES,
      name: "View Page",
      description: "View page details",
      url: "/content/page/detail",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.DELETE_PAGE,
      parent: ROLES.PAGES,
      name: "Delete Page",
      description: "Delete existing pages",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.BULK_PAGE,
      parent: ROLES.PAGES,
      name: "Bulk Page Actions",
      description: "Perform bulk actions on pages",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.FIX_PAGE,
      parent: ROLES.PAGES,
      name: "Fix Page by AI",
      description: "Improve existing pages using AI",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },

    // ─── 4c. Categories ───────────────────────────────────
    {
      _id: ROLES.CATEGORIES,
      parent: ROLES.CONTENT,
      name: "Categories",
      description: "Categories management module",
      url: "/content/category",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.LIST_CATEGORY,
      parent: ROLES.CATEGORIES,
      name: "List Category",
      description: "View categories directory list",
      url: "/content/category",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.CREATE_CATEGORY,
      parent: ROLES.CATEGORIES,
      name: "Create Category",
      description: "Create new categories",
      url: "/content/category/add",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.EDIT_CATEGORY,
      parent: ROLES.CATEGORIES,
      name: "Edit Category",
      description: "Modify existing categories",
      url: "/content/category/edit",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.BULK_CATEGORY,
      parent: ROLES.CATEGORIES,
      name: "Bulk Category Actions",
      description: "Perform bulk actions on categories",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },

    // ─── 4d. Media ────────────────────────────────────────
    {
      _id: ROLES.MEDIA,
      parent: ROLES.CONTENT,
      name: "Media",
      description: "Media management module",
      url: "/content/media",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.LIST_MEDIA,
      parent: ROLES.MEDIA,
      name: "List Media",
      description: "View media library",
      url: "/content/media",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.UPLOAD_MEDIA,
      parent: ROLES.MEDIA,
      name: "Upload Media",
      description: "Upload new media files",
      url: "/content/media/add",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.VIEW_MEDIA,
      parent: ROLES.MEDIA,
      name: "View Media",
      description: "View media details",
      url: "/content/media/detail",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.DELETE_MEDIA,
      parent: ROLES.MEDIA,
      name: "Delete Media",
      description: "Delete media files",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.BULK_MEDIA,
      parent: ROLES.MEDIA,
      name: "Bulk Media Actions",
      description: "Perform bulk actions on media",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },

    // ─── 4e. Ads ─────────────────────────────────────────
    {
      _id: ROLES.ADS,
      parent: ROLES.CONTENT,
      name: "Ads",
      description: "Ad management module",
      url: "/content/ad",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.LIST_AD,
      parent: ROLES.ADS,
      name: "List Ad",
      description: "View ads directory list",
      url: "/content/ad",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.CREATE_AD,
      parent: ROLES.ADS,
      name: "Create Ad",
      description: "Create new ads",
      url: "/content/ad/add",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.EDIT_AD,
      parent: ROLES.ADS,
      name: "Edit Ad",
      description: "Modify existing ads",
      url: "/content/ad/edit",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.DELETE_AD,
      parent: ROLES.ADS,
      name: "Delete Ad",
      description: "Delete ads",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
    {
      _id: ROLES.BULK_AD,
      parent: ROLES.ADS,
      name: "Bulk Ad Actions",
      description: "Perform bulk actions on ads",
      created: { at: now, by: null },
      updated: { at: now, by: null },
    },
  ];

  await roles.insertMany(roleDocs);

  // Link all roles to Administrators group
  const hasRoleDocs = ALL_ROLE_IDS.map((roleId) => ({
    _id: new ObjectId(),
    groupId: ADMIN_GROUP,
    roleId,
    created: { at: now, by: null },
  }));
  await groupHasRole.insertMany(hasRoleDocs);

  // Create compound index
  await groupHasRole.createIndex({ groupId: 1, roleId: 1 }, { unique: true });

  console.log(`Seed complete: ${roleDocs.length} roles upserted and linked to Administrators group.`);
}

seed()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  });
